[2023-12-09T21:56:08.921+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sandbox.segmentation manual__2023-12-09T21:55:35+00:00 [queued]>
[2023-12-09T21:56:08.931+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sandbox.segmentation manual__2023-12-09T21:55:35+00:00 [queued]>
[2023-12-09T21:56:08.931+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-09T21:56:08.939+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): segmentation> on 2023-12-09 21:55:35+00:00
[2023-12-09T21:56:08.948+0000] {standard_task_runner.py:57} INFO - Started process 304 to run task
[2023-12-09T21:56:08.954+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sandbox', 'segmentation', 'manual__2023-12-09T21:55:35+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/sandbox.py', '--cfg-path', '/tmp/tmpatx61ebn']
[2023-12-09T21:56:08.958+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask segmentation
[2023-12-09T21:56:09.003+0000] {task_command.py:416} INFO - Running <TaskInstance: sandbox.segmentation manual__2023-12-09T21:55:35+00:00 [running]> on host 913299e645c2
[2023-12-09T21:56:09.084+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sandbox' AIRFLOW_CTX_TASK_ID='segmentation' AIRFLOW_CTX_EXECUTION_DATE='2023-12-09T21:55:35+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-09T21:55:35+00:00'
[2023-12-09T21:56:09.087+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sandbox.py", line 72, in segmentation
    original_dict = file_reader()
  File "/opt/airflow/dags/sandbox.py", line 33, in file_reader
    epub_path = kwargs["params"]["epub_path"]
KeyError: 'params'
[2023-12-09T21:56:09.099+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sandbox, task_id=segmentation, execution_date=20231209T215535, start_date=20231209T215608, end_date=20231209T215609
[2023-12-09T21:56:09.107+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task segmentation ('params'; 304)
[2023-12-09T21:56:09.128+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-09T21:56:09.147+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
